[package]
name = "reis-finance"
version = "0.1.0"
edition = "2021"

[lib]
name = "reis_finance_lib"
path = "src/lib.rs"

[[bin]]
name = "reis_finance_cli"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.78"
chrono = "0.4.31"
derive_more = "0.99.17"
glob = "0.3.1"
lazy_static = "1.4.0"
polars = {version = "0.36.2", features = ["lazy", "strings", "lazy_regex"]}
strum = {version = "0.25.0", features = ["derive"]}
strum_macros = "0.25.3"
time = {version="0.3.31", features = ["parsing", "formatting"]}
tokio-test = "0.4.3"
yahoo_finance_api = "2.1.0"
