[package]
name = "reis-finance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.78"
glob = "0.3.1"
lazy_static = "1.4.0"
polars = {version = "0.35.4", features = ["lazy", "strings", "is_in"]}
strum = {version = "0.25.0", features = ["derive"]}
strum_macros = "0.25.3"
